# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  packages: !include_dir_named integrations
  customize: !include customize.yaml


http:
  server_port: 8124