description: Send notification on Home Assistant start
alias: system_start_notification
id: c0b37051-2630-41f3-9667-b84dbe597dcb
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.mobile_app_galaxy_s9
    data:
      message: Home Assistant is starting up