- platform: template
  covers:
    garage_door:
      friendly_name: "Garage Door"
      value_template: "{{ is_state('binary_sensor.zigbee_garage_door_sensor_contact', 'on') }}"
      open_cover:
        service: script.turn_on
        target:
          entity_id: script.open_garage_door_with_switchbot
      close_cover:
        service: script.turn_on
        target:
          entity_id: script.close_garage_door_with_switchbot